### PR TITLE
Fix GCMC to use Checkpoint in Config file and python script

### PR DESCRIPTION
**Pull request by GregorySchwing**
Add this line to the config file
"Checkpoint restart_true_or_false Restart_Checkpoint_file"

Delete the entry for a checkpoint file if checkpoint is false:
Checkpoint false

Replace boolean with true and file with relative path to previous GOMC checkpoint output when true.
Checkpoint true ../GOMC_00X/Output_restart.chk

### CODE REVIEW

**Comment by GregorySchwing** [comment]
Do me a favor and run this (I may have messed up indentation) @bc118  since I cant clone the NAMD and GOMC binaries with airport wifi.  Also modify the NVT/NPT/GEMC config files like this one.  There is only one file whether there are 2 or 1 boxes, so just make the exact same changes to each config file.

**Review by bc118 — CHANGES_REQUESTED** [review]
Do not delete these bin files , until an auto build that can replace them is done.

**Review by bc118 — CHANGES_REQUESTED** [review]
Do not delete the examples and the website

**Comment by bc118** [comment]
@GregorySchwing lets not delete everything.  We are only fixing the checkpoint!

**Comment by GregorySchwing** [comment]
Understood.  I had problems with working with the git webpage editing.  I was only trying to delete these in my fork.

**Pull request closed without merging**
